### PR TITLE
Updated materials 

### PR DESCRIPTION
**Pull request by JetteS**
I have updated the preface, the introduction, good practices, and R programming. Minor updates might follow, but nothing major.
I have added a new chapter for the lecture about R Markdown. The chapter is not finished completely; I need to add a section about how to knit the document and the exercise. 

This pull request is quite extensive; I am sorry about that.
The following pull requests will be smaller.

### CODE REVIEW

**Comment by privefl** [comment]
Hi Jette, you did much work on this.

I'm willing to accept most changes, however
- be careful not to change too many things; this is not what we had agreed on (this might be more convenient for you, but it is not for me)
- never delete any previous content; please put everything back (e.g. the examples and exercises on list accessors for data frames, etc)
- be careful not to be too verbose; this might be reassuring for you as a teacher, but you might lose the students (similarly to crowded slides when you make a presentation); try to simplify what you added/modified
- also be careful about the timing when adding content (we already needed to go "fast" on some sessions)

I also made some specific comments on the commits.

**Comment by JetteS** [comment]
Hi Florian,

I haven't deleted any previous content, except for exercise 2 in Section 3.3.3, because I personally don't think the exercise is well suited to show how accessors work. However, I can add the exercise back into the materials if you prefer that. Other than that, I have not removed any content; I have only reordered and added explanations, transitions, etc to make the chapters self-contained.

The reason, I added content, is that I want the students to be able to read the materials on their own. If they read through the materials again in the future, I want them to clearly understand the different topics. I usually have a hard time understanding course materials, if the materials are only in keyword or bullet form and I haven't written them myself. I want to avoid that by making the chapters self-contained. 

Furthermore, I am not adding content to make the teaching job easier for me. I am well aware that large amounts of texts will be confusing for the students and the teacher. As last year, I won't be using the book directly in most cases. As I mentioned before, the reason for adding content is simply to take the reader by the hand and guide them through the materials in the best way possible when I am not physically there to explain things.

**Comment by privefl** [comment]
- Exercise 2 in Section 3.3.3 is important because it makes them work with data frames as lists (when they think data frames are matrices).

- > As last year, I won't be using the book directly in most cases.

  What do you mean? We had this discussion before, and we agreed on using only the book.

- We did agree on adding some content from the R for Data Science book, and this is still missing.

**Comment by privefl** [comment]
Since you won't use these materials for teaching, there is no point for me accepting any changes to the materials.

**Pull request closed without merging**
